RO-Khrixthian-Ibai-M-aximo/Sprint1
infabeti/RO-Khrixthian-Ibai-Maximo-Quintana pull request #1
Opened 2020-10-05 07:17 UTC by maximohernandezga

Hola, todavía no conseguimos leer desde .docx, estamos en ello. Pero leemos ya 5 tipos de archivos diferentes

2020-10-05 17:40 UTC, infabeti commented on .metadata/.plugins/org.eclipse.core.resources/.history/23/d0084cc08002001b1daedfe7fc95c257
> +public class Library {
borra esto

2020-10-05 17:40 UTC, infabeti commented on .metadata/.plugins/org.eclipse.core.resources/.history/9e/508659f98202001b1daedfe7fc95c257
> +
Borra todos los history en master solo tenemos código definitivo

2020-10-05 17:41 UTC, infabeti commented on .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
> +
Estos archivos para que son?

2020-10-05 17:42 UTC, infabeti commented on .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.egit.core.prefs
> +GitRepositoriesView.GitDirectories=E\:\\DESARROLLO DE APLICACIONES MULTIMEDIA\\2 ANYO\\PSP\\pspdiario\\PSP\\.git;E\:\\DESARROLLO DE APLICACIONES MULTIMEDIA\\2 ANYO\\PSP\\git\\PSP\\.git;E\:\\DESARROLL
Porque apunta a E??

2020-10-05 17:44 UTC, infabeti requested changes
Os iba a revisar el código. Pero, me he encontrado con 194 archivos. Tenéis que aligerar el proyecto, porque es imposible que os reviso todo eso. Me da a la nariz que mas de la mitad de los archivos no sirven para nada. Limpiar el proyecto por favor.

2020-10-06 06:16 UTC, maximohernandezga commented on .metadata/.plugins/org.eclipse.core.resources/.history/23/d0084cc08002001b1daedfe7fc95c257
> +public class Library {
Hecho

2020-10-06 06:20 UTC, maximohernandezga commented on .metadata/.plugins/org.eclipse.core.resources/.history/9e/508659f98202001b1daedfe7fc95c257
> +
Borrados todos los archivos de .history

2020-10-06 06:23 UTC, maximohernandezga commented on .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
> +
No sabemos, lo hemos borrado.

2020-10-06 09:45 UTC, maximohernandezga commented on .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.egit.core.prefs
> +GitRepositoriesView.GitDirectories=E\:\\DESARROLLO DE APLICACIONES MULTIMEDIA\\2 ANYO\\PSP\\pspdiario\\PSP\\.git;E\:\\DESARROLLO DE APLICACIONES MULTIMEDIA\\2 ANYO\\PSP\\git\\PSP\\.git;E\:\\DESARROLL
Lo hemos borrado.

2020-10-06 10:05 UTC, maximohernandezga commented
> Os iba a revisar el código. Pero, me he encontrado con 194 archivos. Tenéis que aligerar el proyecto, porque es imposible que os reviso todo eso. Me da a la nariz que mas de la mitad de los archivos no sirven para nada. Limpiar el proyecto por favor.

>Hemos aligerado el proyecto de cara a la presentación de mañana, por si te da tiempo a hechar un ojo al código.
Gracias

2020-10-06 20:08 UTC, infabeti commented
> 
> 
> > Os iba a revisar el código. Pero, me he encontrado con 194 archivos. Tenéis que aligerar el proyecto, porque es imposible que os reviso todo eso. Me da a la nariz que mas de la mitad de los archivos no sirven para nada. Limpiar el proyecto por favor.
> 
> > Hemos aligerado el proyecto de cara a la presentación de mañana, por si te da tiempo a hechar un ojo al código.
> > Gracias

Seguis teniendo 184 archivos chicos

2020-10-07 20:11 UTC, maximohernandezga commented
Hemos aligerado el sprint1. Entre las carpetas ficheros, imagenes, librerias y src son unos 40 ficheros, el resto son los de configuración del gradle y el git.

2020-10-08 09:41 UTC, maximohernandezga commented
Hemos limpiado todo lo que hemos sabido. Del sprint1 nos quedan 81 archivos y 26 carpetas. Para acortar más ya tendríamos que agrupar clases, es decir, ahora para cada tipo de archivo teníamos una clase en modelo y otra en controladores, podríamos dejar una sola clase en modelo y otra en controlador. En principio nos pareció más claro separarlas, de cara a los test y el reparto de tareas entre nosotros.

2020-10-08 13:19 UTC, infabeti commented on src/main/java/controlador/ControladorUser.java
> +		boolean control;
declararlo private

2020-10-08 13:19 UTC, infabeti commented on src/main/java/controlador/ControladorUser.java
> +	ModeloUsers modeloUsers;
Es publico, privado? Hay que ponerlo.

2020-10-08 13:20 UTC, infabeti commented on src/main/java/controlador/GesOds.java
> +public class GesOds {
Pegale un intro. Intenta que te queden todas las clases igual

2020-10-08 13:20 UTC, infabeti commented on src/main/java/controlador/GesOdt.java
> +	public String mostrarOdt() {
+1

2020-10-08 13:20 UTC, infabeti commented on src/main/java/controlador/GesTxt.java
> +	}
+1

2020-10-08 13:21 UTC, infabeti commented on src/main/java/modelo/LeerHtml.java
> +		String total = "";
Estas variables no deberian ser privadas? No están alineadas!!

2020-10-08 13:22 UTC, infabeti commented on src/main/java/modelo/LeerHtml.java
> +	public static String muestraContenido() {
Tiene que ser estático, no se podría hacer más de una instancia en ningún caso?

2020-10-08 13:22 UTC, infabeti commented on src/main/java/modelo/LeerHtml.java
> +			archivo = "ficheros\\Usuarios.html";
Declara una variable estática para esto

2020-10-08 13:23 UTC, infabeti commented on src/main/java/modelo/LeerHtml.java
> +			while((cadena = b.readLine())!=null) {
Tabula a la izquierda

2020-10-08 13:23 UTC, infabeti commented on src/main/java/modelo/LeerHtml.java
> +			b.close();
+1

2020-10-08 13:23 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +	public static String LecturadOds() {
Tiene que ser estático?

2020-10-08 13:24 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +		File archivo = new File(Dir);
Estas no deberían ser privadas?

2020-10-08 13:24 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +		String Dir = ".//ficheros//Prestamos.ods";
Declara una variable estática

2020-10-08 13:24 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +			int nColumnas = sheet.getColumnCount();
Las variables las declaramos o bien fuera o al principio del programa

2020-10-08 13:25 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +			contenidoOds += "\n";
Tal vez puedas usar string format???

2020-10-08 13:26 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
> +		String Dir = ".//ficheros//trabajadores.odt";
variable estática?

2020-10-08 13:26 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
> +		File archivo = new File(Dir);
private?

2020-10-08 13:26 UTC, infabeti commented on src/main/java/modelo/LeerTxt.java
> +		String ruta = ".\\ficheros\\Libros.txt";
private? ruta estático?

2020-10-08 13:27 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +		contenidotXml.clear();
private?

2020-10-08 13:27 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +			Document documento = builder.parse(new File(".//ficheros//videoteca.xml"));
Declaramos o arriba o afuera

2020-10-08 13:27 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +			NodeList hijos = archivo.getChildNodes();
+1

2020-10-08 13:28 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +							contenidotXml.addElement("Pelicula: " + hijo.getNodeName() + ": " + hijo.getTextContent());
string format?

2020-10-08 13:28 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +			contenidotXml.addElement("Nodo raiz: " + archivo.getNodeName());
string format?

2020-10-08 13:28 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +			contenidotXml.addElement("Nodo hijo: " + hijos.item(1).getNodeName());
+1

2020-10-08 13:29 UTC, infabeti commented on src/main/java/modelo/ModeloUsers.java
> +		Matcher matcher = patron.matcher(texto);
private?

2020-10-08 13:29 UTC, infabeti commented on src/main/java/modelo/modeloLectura.java
> +		String path = "C:\\Users\\IN2DAM\\Desktop\\wordprueba.docx";
Estatico?

2020-10-08 13:29 UTC, infabeti commented on src/main/java/modelo/modeloLectura.java
> +			XWPFDocument docu = new XWPFDocument(fps);
private? Lo declaramos arriba?

2020-10-08 13:30 UTC, infabeti commented on src/main/java/modelo/modeloLectura.java
> +		}
si teneis dos catch distintos añadir un mensaje a cada una de las trazas para que podamos saber por donde a roto

2020-10-08 13:31 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +	JTextPane textPane = new JTextPane();
Este no es private?

2020-10-08 13:33 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				GesTxt infoTxt = new GesTxt();
Casi que mejor si le cambiais el nombre a todas las clases que sean de controlador para que quede más claro que se está recogiendo de ahí la información

2020-10-08 13:33 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				GesTxt infoTxt = new GesTxt();
Llamadle ControladorGestTxt a la clase

2020-10-08 13:33 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				GesXml infoXml = new GesXml();
+1

2020-10-08 13:33 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				GesHtml infoHtml = new GesHtml();
+1

2020-10-08 13:34 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				GesOdt infoOdt = new GesOdt();
+1

2020-10-08 13:34 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				GesOds infoOds = new GesOds();
+1

2020-10-08 13:34 UTC, infabeti commented on src/main/java/vista/VentanaUser.java
> +	ControladorUser controladorUser = new ControladorUser();
pon public

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/ControladorUserTest.java
> +	ControladorUser controladorUser = new ControladorUser();
private

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/ControladorUserTest.java
> +		boolean resultado = controladorUser.validarContrasena("letra1");
private

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/ControladorUserTest.java
> +		boolean resultado = controladorUser.validarContrasena("�����");
private

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/GesHtmlTest.java
> +	GesHtml testGesHtml = new GesHtml();
private

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/GesOdsTest.java
> +	GesOds testGesOds = new GesOds();
private

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/GesOdtTest.java
> +	GesOdt testGesOdt = new GesOdt();
private

2020-10-08 13:36 UTC, infabeti commented on src/test/java/controlador/GesTxtTest.java
> +	GesTxt testGesTxt = new GesTxt();
private

2020-10-08 13:37 UTC, infabeti commented on src/test/java/controlador/GesXmlTest.java
> +	GesXml testGesXml = new GesXml();
private

2020-10-08 13:37 UTC, infabeti commented on src/test/java/controlador/GesXmlTest.java
> +		resultadoesperado = "Nodo raiz: videoteca" + (char) 10
+1

2020-10-08 13:38 UTC, infabeti commented on src/test/java/modelo/LeerHtmlTest.java
> +	LeerHtml testhtml = new LeerHtml();
+1

2020-10-08 13:38 UTC, infabeti commented on src/test/java/modelo/LeerHtmlTest.java
> +		resultado = testhtml.muestraContenido();
+1

2020-10-08 13:38 UTC, infabeti commented on src/test/java/modelo/LeerHtmlTest.java
> +		System.out.println(resultado);
Borrad esto

2020-10-08 13:38 UTC, infabeti commented on src/test/java/modelo/LeerOdsTest.java
> +	LeerOds testods = new LeerOds();
+1

2020-10-08 13:38 UTC, infabeti commented on src/test/java/modelo/LeerOdsTest.java
> +		System.out.println(resultado);
borra esto

2020-10-08 13:39 UTC, infabeti commented on src/test/java/modelo/LeerTxtTest.java
> +	LeerTxt testtxt = new LeerTxt();
+1

2020-10-08 13:39 UTC, infabeti commented on src/test/java/modelo/LeerTxtTest.java
> +		resultado = testtxt.leertxt();
+1

2020-10-08 13:39 UTC, infabeti commented on src/test/java/modelo/LeerXmlTest.java
> +	LeerXml testxml = new LeerXml();
+1

2020-10-08 13:39 UTC, infabeti commented on src/test/java/modelo/ModeloUsersTest.java
> +		boolean resultado = modeloUsers.validarSoloAlfanumerico("numero1");
private

2020-10-08 13:40 UTC, infabeti requested changes
Os he puesto un par de cosillas. Pero, en general lo teneis muy bien. Buen trabajo! 

Veo que teneis problemas con el formato (tabulaciones, intros, etc.). Porque, no intentais poner un linter?

2020-10-08 13:57 UTC, infabeti commented
Os he hecho un par de comentarios.

El jue., 8 oct. 2020 a las 11:41, maximohernandezga (<
notifications@github.com>) escribió:

> Hemos limpiado todo lo que hemos sabido. Del sprint1 nos quedan 81
> archivos y 26 carpetas. Para acortar más ya tendríamos que agrupar clases,
> es decir, ahora para cada tipo de archivo teníamos una clase en modelo y
> otra en controladores, podríamos dejar una sola clase en modelo y otra en
> controlador. En principio nos pareció más claro separarlas, de cara a los
> test y el reparto de tareas entre nosotros.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/infabeti/RO-Khrixthian-Ibai-Maximo-Quintana/pull/1#issuecomment-705455948>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKIEZIT3JYSZJU63A5GUBTLSJWCM5ANCNFSM4SEJ3RQQ>
> .
>

2020-10-08 18:31 UTC, maximohernandezga commented on src/test/java/controlador/ControladorUserTest.java
> +		boolean resultado = controladorUser.validarContrasena("letra1");
Poniendo private a los test true y false, lineas 12 y 20, falla el test y el rastreo de la anomalía dice que el método debe ser público. Por eso seguimos dejando public.

2020-10-08 18:33 UTC, maximohernandezga commented on src/test/java/controlador/ControladorUserTest.java
> +		boolean resultado = controladorUser.validarContrasena("�����");
¿En los parámetros?

2020-10-08 18:43 UTC, maximohernandezga commented on src/test/java/controlador/GesXmlTest.java
> +		resultadoesperado = "Nodo raiz: videoteca" + (char) 10
¿En los parámetros dentro del método test()?.  Con "private" me dice modificador no permitido, sólo vale "final"

2020-10-08 18:48 UTC, maximohernandezga commented on src/test/java/modelo/LeerHtmlTest.java
> +		resultado = testhtml.muestraContenido();
¿?. Poniendo "private" en el método falla el test.

2020-10-08 18:57 UTC, maximohernandezga commented on src/test/java/modelo/LeerTxtTest.java
> +		resultado = testtxt.leertxt();
Como los demás, con private en el método, falla. En cuanto a las variables internas del test() ¿Te refieres a usemos variables específicas de cada test y no usemos resultado y resultadoesperado como globales?

2020-10-08 19:12 UTC, maximohernandezga commented on src/test/java/modelo/ModeloUsersTest.java
> +		boolean resultado = modeloUsers.validarSoloAlfanumerico("numero1");
Añadidas las declaraciones como globales y "private boolean". Igual que en su controlador correspondiente.

2020-10-08 19:19 UTC, maximohernandezga commented on src/main/java/modelo/modeloLectura.java
> +		String path = "C:\\Users\\IN2DAM\\Desktop\\wordprueba.docx";
Cambiado. 
Como comentario, este tipo de archivo, el .docx no lo conseguimos leer. Estamos en ello, lo tenemos como pendiente y esperamos arreglarlo antes del sprint2

2020-10-08 19:20 UTC, maximohernandezga commented on src/main/java/modelo/modeloLectura.java
> +			XWPFDocument docu = new XWPFDocument(fps);
Sin cambiar, es donde nos falla el código, que no encuentra la libreria. Estamos en ello

2020-10-08 19:21 UTC, maximohernandezga commented on src/main/java/modelo/modeloLectura.java
> +		}
Corregido

2020-10-08 19:21 UTC, maximohernandezga commented on src/main/java/vista/VentanaConsultas.java
> +	JTextPane textPane = new JTextPane();
Corregido

2020-10-08 19:21 UTC, maximohernandezga commented on src/main/java/vista/VentanaConsultas.java
> +				GesTxt infoTxt = new GesTxt();
Cambiado, este y todos los controladores, tanto del main, como del test

2020-10-08 19:23 UTC, maximohernandezga commented on src/main/java/vista/VentanaConsultas.java
> +				GesXml infoXml = new GesXml();
Cambiado, este y todos los controladores, tanto del main, como del test

2020-10-08 19:23 UTC, maximohernandezga commented on src/main/java/vista/VentanaConsultas.java
> +				GesHtml infoHtml = new GesHtml();
Cambiado, este y todos los controladores, tanto del main, como del test

2020-10-08 19:23 UTC, maximohernandezga commented on src/main/java/vista/VentanaConsultas.java
> +				GesOdt infoOdt = new GesOdt();
Cambiado, este y todos los controladores, tanto del main, como del test

2020-10-08 19:23 UTC, maximohernandezga commented on src/main/java/vista/VentanaConsultas.java
> +				GesOds infoOds = new GesOds();
Cambiado, este y todos los controladores, tanto del main, como del test

2020-10-08 19:24 UTC, maximohernandezga commented on src/main/java/vista/VentanaUser.java
> +	ControladorUser controladorUser = new ControladorUser();
puesto

2020-10-08 19:25 UTC, maximohernandezga commented on src/test/java/controlador/ControladorUserTest.java
> +	ControladorUser controladorUser = new ControladorUser();
puesto

2020-10-08 19:27 UTC, maximohernandezga commented on src/test/java/controlador/GesHtmlTest.java
> +	GesHtml testGesHtml = new GesHtml();
puesto

2020-10-08 19:27 UTC, maximohernandezga commented on src/test/java/controlador/GesOdsTest.java
> +	GesOds testGesOds = new GesOds();
puesto

2020-10-08 19:27 UTC, maximohernandezga commented on src/test/java/controlador/GesOdtTest.java
> +	GesOdt testGesOdt = new GesOdt();
puestos

2020-10-08 19:27 UTC, maximohernandezga commented on src/test/java/controlador/GesTxtTest.java
> +	GesTxt testGesTxt = new GesTxt();
puestos

2020-10-08 19:27 UTC, maximohernandezga commented on src/test/java/controlador/GesXmlTest.java
> +	GesXml testGesXml = new GesXml();
puestos

2020-10-08 19:29 UTC, maximohernandezga commented on src/test/java/controlador/GesXmlTest.java
> +		resultadoesperado = "Nodo raiz: videoteca" + (char) 10
igual que en el otro controlador, declarados arriba.

2020-10-08 19:30 UTC, maximohernandezga commented on src/test/java/modelo/LeerHtmlTest.java
> +	LeerHtml testhtml = new LeerHtml();
puestos

2020-10-08 19:31 UTC, maximohernandezga commented on src/test/java/modelo/LeerHtmlTest.java
> +		System.out.println(resultado);
borrado

2020-10-08 19:32 UTC, maximohernandezga commented on src/test/java/modelo/LeerOdsTest.java
> +	LeerOds testods = new LeerOds();
puestos los private

2020-10-08 19:32 UTC, maximohernandezga commented on src/test/java/modelo/LeerOdsTest.java
> +		System.out.println(resultado);
borrado

2020-10-08 19:32 UTC, maximohernandezga commented on src/test/java/modelo/LeerTxtTest.java
> +	LeerTxt testtxt = new LeerTxt();
puestos

2020-10-08 19:33 UTC, maximohernandezga commented on src/test/java/modelo/LeerTxtTest.java
> +		resultado = testtxt.leertxt();
corregido

2020-10-08 19:33 UTC, maximohernandezga commented on src/test/java/modelo/LeerXmlTest.java
> +	LeerXml testxml = new LeerXml();
puestos

2020-10-09 06:21 UTC, infabeti commented on src/main/java/modelo/modeloLectura.java
> +	public static void main(String[] args) throws IOException, FileNotFoundException  {
Quita este main

2020-10-09 07:17 UTC, maximohernandezga commented on src/main/java/modelo/modeloLectura.java
> +	public static void main(String[] args) throws IOException, FileNotFoundException  {
quitado

2020-10-09 07:57 UTC, maximohernandezga commented on src/main/java/controlador/ControladorUser.java
> +		boolean control;
hecho

2020-10-09 07:57 UTC, maximohernandezga commented on src/main/java/controlador/ControladorUser.java
> +	ModeloUsers modeloUsers;
puesto

2020-10-09 07:58 UTC, maximohernandezga commented on src/main/java/controlador/GesOds.java
> +public class GesOds {
formateado el código

2020-10-09 07:58 UTC, maximohernandezga commented on src/main/java/controlador/GesOdt.java
> +	public String mostrarOdt() {
=

2020-10-09 07:58 UTC, maximohernandezga commented on src/main/java/controlador/GesTxt.java
> +	}
=

2020-10-09 07:59 UTC, maximohernandezga commented on src/main/java/modelo/LeerHtml.java
> +		String total = "";
puestas y alineadas

2020-10-09 07:59 UTC, maximohernandezga commented on src/main/java/modelo/LeerHtml.java
> +	public static String muestraContenido() {
quitado es static y creada la instancia en el controlador

2020-10-09 08:00 UTC, maximohernandezga commented on src/main/java/modelo/LeerHtml.java
> +			archivo = "ficheros\\Usuarios.html";
declarada

2020-10-09 08:00 UTC, maximohernandezga commented on src/main/java/modelo/LeerHtml.java
> +			while((cadena = b.readLine())!=null) {
formateado el código

2020-10-09 08:00 UTC, maximohernandezga commented on src/main/java/modelo/LeerHtml.java
> +			b.close();
=

2020-10-09 08:00 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +	public static String LecturadOds() {
quitado es static y creada la instancia en el controlador

2020-10-09 08:00 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +		File archivo = new File(Dir);
puestas

2020-10-09 08:01 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +		String Dir = ".//ficheros//Prestamos.ods";
declarada

2020-10-09 08:02 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +			int nColumnas = sheet.getColumnCount();
puestas las declaraciones arriba

2020-10-09 08:02 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +			contenidoOds += "\n";
Pte.

2020-10-09 08:02 UTC, maximohernandezga commented on src/main/java/modelo/LeerOdt.java
> +		String Dir = ".//ficheros//trabajadores.odt";
puesta

2020-10-09 08:02 UTC, maximohernandezga commented on src/main/java/modelo/LeerOdt.java
> +		File archivo = new File(Dir);
puestas

2020-10-09 08:02 UTC, maximohernandezga commented on src/main/java/modelo/LeerTxt.java
> +		String ruta = ".\\ficheros\\Libros.txt";
puestas

2020-10-09 08:03 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +		contenidotXml.clear();
puesta

2020-10-09 08:03 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +			Document documento = builder.parse(new File(".//ficheros//videoteca.xml"));
Declaradas

2020-10-09 08:03 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +			NodeList hijos = archivo.getChildNodes();
=

2020-10-09 08:03 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +							contenidotXml.addElement("Pelicula: " + hijo.getNodeName() + ": " + hijo.getTextContent());
Pte.

2020-10-09 08:03 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +			contenidotXml.addElement("Nodo raiz: " + archivo.getNodeName());
Pte.

2020-10-09 08:03 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +			contenidotXml.addElement("Nodo hijo: " + hijos.item(1).getNodeName());
declaradas fuera

2020-10-09 08:04 UTC, maximohernandezga commented on src/main/java/modelo/ModeloUsers.java
> +		Matcher matcher = patron.matcher(texto);
puestas

2020-10-09 08:06 UTC, maximohernandezga commented
Ya hemos contestado todo, sólo falta los 3 string format que haremos a la
tarde.

El vie., 9 oct. 2020 a las 8:21, infabeti (<notifications@github.com>)
escribió:

> *@infabeti* commented on this pull request.
> ------------------------------
>
> In src/main/java/modelo/modeloLectura.java
> <https://github.com/infabeti/RO-Khrixthian-Ibai-Maximo-Quintana/pull/1#discussion_r502211764>
> :
>
> > @@ -0,0 +1,40 @@
> +package modelo;
> +
> +import java.io.FileInputStream;
> +import java.io.FileNotFoundException;
> +import java.io.IOException;
> +import java.util.List;
> +
> +import org.apache.poi.xwpf.usermodel.XWPFDocument;
> +import org.apache.poi.xwpf.usermodel.XWPFParagraph;
> +
> +
> +public class modeloLectura {
> +	
> +	public static void main(String[] args) throws IOException, FileNotFoundException  {
>
> Quita este main
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/infabeti/RO-Khrixthian-Ibai-Maximo-Quintana/pull/1#pullrequestreview-505390402>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOPCCQ23CLQY4PVSLZYG3RTSJ2TWZANCNFSM4SEJ3RQQ>
> .
>

2020-10-09 10:55 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +			contenidoOds += "\n";
Añadido String format ya en el último commit

2020-10-09 10:55 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +							contenidotXml.addElement("Pelicula: " + hijo.getNodeName() + ": " + hijo.getTextContent());
Añadido String format ya en el último commit

2020-10-09 10:56 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +			contenidotXml.addElement("Nodo raiz: " + archivo.getNodeName());
Añadido String format ya en el último commit

2020-10-09 10:57 UTC, maximohernandezga commented
Ya hemos incorporado todos los comentarios

2020-10-09 11:15 UTC, infabeti commented on src/main/java/controlador/ControladorGesHtml.java
> +		LeerHtml leerHtml = new LeerHtml();
Podría ser private?

2020-10-09 11:16 UTC, infabeti commented on src/main/java/controlador/ControladorGesOds.java
> +	LeerOds leerOds = new LeerOds();
private?

2020-10-09 11:17 UTC, infabeti commented on src/main/java/controlador/ControladorGesOdt.java
> +		return LeerOdt.LecturadOdt();
Este sigue siendo estático?

2020-10-09 11:18 UTC, infabeti commented on src/main/java/controlador/ControladorUser.java
> +		boolean control;
Las declaraciones primero. Y, lo inicializamos.

2020-10-09 11:19 UTC, infabeti commented on src/main/java/modelo/LeerHtml.java
> +    private static FileReader f = null;
Está mal tabulado. Poned un lintern en el siguiente sprint

2020-10-09 11:20 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +	private static String Dir = ".//ficheros//Prestamos.ods";
los static los ponemos en mayúscula. Para poder identificarlos de una lectura.

2020-10-09 11:20 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
> +	// Obtengo el documento, a partir del Odt
+1

2020-10-09 11:21 UTC, infabeti commented on src/main/java/modelo/LeerTxt.java
> +	private static String ruta = ".//ficheros//Libros.txt";
+1

2020-10-09 11:22 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +	private static String Dir = ".//ficheros//Prestamos.ods";
No es static es final

2020-10-09 11:22 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
> +	// Obtengo el documento, a partir del Odt
No es static es final

2020-10-09 11:23 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
> +	private static String contenidoOdt = "";
Este parece que no deberia de ser static

2020-10-09 11:23 UTC, infabeti commented on src/main/java/modelo/LeerXml.java
> +	private static String textoXml = "";
este no deberia de ser static

2020-10-09 11:24 UTC, infabeti commented on src/main/java/modelo/modeloLectura.java
> +		String path = ".//ficheros//CDs.docx";
Este parece candidato a final

2020-10-09 11:27 UTC, infabeti commented on src/test/java/modelo/LeerHtmlTest.java
> +		} ;
Esto no lo tiene que hacer el test. Sino el método

2020-10-09 11:28 UTC, infabeti commented on src/test/java/modelo/LeerOdsTest.java
> +		if (resultado != null) {
Esto lo debería hacer el método

2020-10-09 11:29 UTC, infabeti requested changes
Os he puesto un par de detalles. Ya lo tenéis casi.

2020-10-09 20:53 UTC, maximohernandezga commented on src/main/java/controlador/ControladorGesOds.java
> +	LeerOds leerOds = new LeerOds();
cambiado

2020-10-09 20:54 UTC, maximohernandezga commented on src/main/java/controlador/ControladorGesOdt.java
> +		return LeerOdt.LecturadOdt();
cambiado

2020-10-09 20:54 UTC, maximohernandezga commented on src/main/java/controlador/ControladorUser.java
> +		boolean control;
hecho

2020-10-09 20:55 UTC, maximohernandezga commented on src/main/java/modelo/LeerOds.java
> +	private static String Dir = ".//ficheros//Prestamos.ods";
cambiados

2020-10-09 20:55 UTC, maximohernandezga commented on src/main/java/modelo/LeerOdt.java
> +	// Obtengo el documento, a partir del Odt
cambiados

2020-10-09 20:55 UTC, maximohernandezga commented on src/main/java/modelo/LeerTxt.java
> +	private static String ruta = ".//ficheros//Libros.txt";
=

2020-10-09 20:56 UTC, maximohernandezga commented on src/main/java/modelo/LeerOdt.java
> +	private static String contenidoOdt = "";
quitado

2020-10-09 20:56 UTC, maximohernandezga commented on src/main/java/modelo/LeerXml.java
> +	private static String textoXml = "";
=

2020-10-09 20:56 UTC, maximohernandezga commented on src/main/java/modelo/modeloLectura.java
> +		String path = ".//ficheros//CDs.docx";
puesto como final

2020-10-09 20:57 UTC, maximohernandezga commented on src/test/java/modelo/LeerHtmlTest.java
> +		} ;
cambiado, ahora igual que el test del controlador

2020-10-09 20:57 UTC, maximohernandezga commented on src/test/java/modelo/LeerOdsTest.java
> +		if (resultado != null) {
cambiado, ahora igual que el test del controlador

2020-10-09 21:04 UTC, maximohernandezga commented
Hechos los cambios. Ya hemos acertado a leer los .docx, así que también hemos incorporado las correcciones en este sprint. El nuevo código incorporado ha sido añadir librerías, ajustar el código del modelo, ponerle el controlador y la acción del botón en la ventana: Modelo.LeerDocx, Controlador.ControladorGesDocx y Vista.VentanaConsultas (lineas de 171 a 181 )
Ahora, ya leemos los 6 formatos.

Perdón por las horas.

2020-10-10 07:41 UTC, infabeti approved these changes
Sigue habiendo cosas que cambiaría. Pero, lo vamos a mergear porque sino podemos estar hasta el fin del mundo haciendo mejoras

2020-10-10 07:42 UTC, merged

2020-10-16 08:56 UTC, infabeti commented on src/main/java/modelo/LeerDocx.java
> +			XWPFDocument docu = new XWPFDocument(fps);
trghjhhytftf6huyo87tf

2020-10-16 08:56 UTC, infabeti reviewed
te lo he zfdszfxdfgxfggcfcg

2020-10-16 10:35 UTC, DiegoVJElorrieta commented on src/main/java/modelo/LeerDocx.java
> +			XWPFDocument docu = new XWPFDocument(fps);
Estas haciendo pruebas? O tenemos que cambiar algo, ya que este sprint esta cerrado.

2020-10-16 10:51 UTC, infabeti commented on src/main/java/modelo/LeerDocx.java
> +			XWPFDocument docu = new XWPFDocument(fps);
Si, lo siento, estaba explicando a una compañera. Creía que no llegaban los mensajes en un pull request cerrado

2020-10-16 11:27 UTC, DiegoVJElorrieta commented on src/main/java/modelo/LeerDocx.java
> +			XWPFDocument docu = new XWPFDocument(fps);
Okay, entonces perfecto 👌