Sprint3
infabeti/RO-Khrixthian-Ibai-Maximo-Quintana pull request #3
Opened 2020-10-23 18:47 UTC by khrixthian

Hola Ander te enviamos ya el pull request del sprint3 a ver que tal lo ves.
un saludo

2020-10-26 08:51 UTC, infabeti commented on src/main/java/controlador/ControladorGesEscDocx.java
> +		agregarAlDocx.EscribirDocx(x);
this.agregarAlDocx.EscribirDocx(x);

2020-10-26 08:52 UTC, infabeti commented on src/main/java/controlador/ControladorGesEscHtml.java
> +		agregarAlHtml.agregar(x);
pon el this

2020-10-26 08:52 UTC, infabeti commented on src/main/java/controlador/ControladorGesEscOdt.java
> +		agregarAlOdt.EscribirOdt(x);
+1

2020-10-26 08:52 UTC, infabeti commented on src/main/java/controlador/ControladorGesEscTxt.java
> +		agregarTxt.agregar(x);
+1

2020-10-26 08:53 UTC, infabeti commented on src/main/java/controlador/ControladorGesTxt.java
> +	private FileReader x;
Suele ser recomendable el iniciarlo por si acaso

2020-10-26 08:54 UTC, infabeti commented on src/main/java/modelo/AgregarAlDocx.java
> +			FileOutputStream fos = new FileOutputStream(".//ficheros//CDs.docx");
En nombre del archivo no lo podemos declarar como un final?

2020-10-26 08:55 UTC, infabeti commented on src/main/java/modelo/AgregarAlTxt.java
> +	LeerTxt aaa = new LeerTxt();
Este no sería private? aaa es un buen nombre para una variable?

2020-10-26 08:55 UTC, infabeti commented on src/main/java/modelo/AgregarAlTxt.java
> +			ruta = ".//ficheros//Libros.txt";
nombre candidato a final

2020-10-26 08:56 UTC, infabeti commented on src/main/java/modelo/AgregarAlTxt.java
> +			ruta = ".//ficheros//Libros.txt";
esta linea está repetida

2020-10-26 08:58 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +			for(int i = 0; i < nFilas; i++) {
Me parece que podrías hacer un método para esta funcionalidad

2020-10-26 08:58 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
>  	private static String Dir = ".//ficheros//trabajadores.odt";
final?

2020-10-26 08:59 UTC, infabeti commented on src/main/java/modelo/LeerTxt.java
>  		String ruta = ".//ficheros//Libros.txt";
final?

2020-10-26 09:00 UTC, infabeti commented on src/main/java/modelo/LeerTxt.java
> +			x = new FileReader(ruta);
x no es muy representativo

2020-10-26 09:00 UTC, infabeti commented on src/main/java/modelo/VariablesEstaticas.java
> +	public static String[][] MatrizAuxiliarString;
No tiene pinta de que sea necesario que la matriz auxiliar sea estática

2020-10-26 09:01 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		ControladorGesDocx aaa = new ControladorGesDocx();
aaa?

2020-10-26 09:03 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		String aux = aaa.mostrarDocx();
No creo que aux sea un nombre adecuado

2020-10-26 09:08 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		String aux = aaa.mostrarDocx();
Porque llamas a mostrarDocx en el test de gesEscDocx???

2020-10-26 09:08 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +	public void Testdocx() {
Revisa el nombre del test

2020-10-26 09:08 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscHtmltest.java
> +	public void testHtml() {
lo mismo que en el otro

2020-10-26 09:08 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscOdtTest.java
> +	public void name() {
+1

2020-10-26 09:09 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscTxtTest.java
> +	public void name() {
+1

2020-10-26 09:10 UTC, infabeti requested changes
Os he puesto un par de comentarios. Animo que llegais para la demo

2020-10-26 21:05 UTC, khrixthian commented on src/main/java/controlador/ControladorGesEscDocx.java
> +		agregarAlDocx.EscribirDocx(x);
arreglado

2020-10-26 21:05 UTC, khrixthian commented on src/main/java/controlador/ControladorGesEscHtml.java
> +		agregarAlHtml.agregar(x);
arreglado

2020-10-26 21:05 UTC, khrixthian commented on src/main/java/controlador/ControladorGesEscOdt.java
> +		agregarAlOdt.EscribirOdt(x);
arreglado

2020-10-26 21:06 UTC, khrixthian commented on src/main/java/controlador/ControladorGesEscTxt.java
> +		agregarTxt.agregar(x);
arreglado

2020-10-26 21:06 UTC, khrixthian commented on src/main/java/controlador/ControladorGesTxt.java
> +	private FileReader x;
iniciado

2020-10-26 21:06 UTC, khrixthian commented on src/main/java/modelo/AgregarAlDocx.java
> +			FileOutputStream fos = new FileOutputStream(".//ficheros//CDs.docx");
ok, lo hemos puesto como final

2020-10-26 21:07 UTC, khrixthian commented on src/main/java/modelo/AgregarAlTxt.java
> +	LeerTxt aaa = new LeerTxt();
lo hemos puesto privado y cambiado el nombre

2020-10-26 21:07 UTC, khrixthian commented on src/main/java/modelo/AgregarAlTxt.java
> +			ruta = ".//ficheros//Libros.txt";
arreglado

2020-10-26 21:07 UTC, khrixthian commented on src/main/java/modelo/AgregarAlTxt.java
> +			ruta = ".//ficheros//Libros.txt";
arreglado

2020-10-26 21:07 UTC, khrixthian commented on src/main/java/modelo/LeerOds.java
> +			for(int i = 0; i < nFilas; i++) {
hecho el método.

2020-10-26 21:08 UTC, khrixthian commented on src/main/java/modelo/LeerOdt.java
>  	private static String Dir = ".//ficheros//trabajadores.odt";
lo pusimos final

2020-10-26 21:08 UTC, khrixthian commented on src/main/java/modelo/LeerTxt.java
>  		String ruta = ".//ficheros//Libros.txt";
arreglado

2020-10-26 21:08 UTC, khrixthian commented on src/main/java/modelo/LeerTxt.java
> +			x = new FileReader(ruta);
toda la razón, lo hemos cambiado

2020-10-26 21:09 UTC, khrixthian commented on src/main/java/modelo/VariablesEstaticas.java
> +	public static String[][] MatrizAuxiliarString;
Lo hemos tenido que dejar en static porque nos influye en demasiados sitios.

2020-10-26 21:10 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		ControladorGesDocx aaa = new ControladorGesDocx();
arreglado

2020-10-26 21:10 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		String aux = aaa.mostrarDocx();
arreglado lo de aux.
lo dejamos de llamar.

2020-10-26 21:10 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +	public void Testdocx() {
arreglado

2020-10-26 21:10 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscHtmltest.java
> +	public void testHtml() {
+1

2020-10-26 21:10 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscOdtTest.java
> +	public void name() {
+1

2020-10-26 21:11 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscTxtTest.java
> +	public void name() {
arreglado

2020-10-26 21:12 UTC, khrixthian commented
Salvo una hemos arreglado todo, respondidos todos los comentarios.

2020-10-28 07:09 UTC, infabeti commented on src/main/java/modelo/AgregarAlTxt.java
> +			aux = auxorigen + nuevoFormateado;
Un método nuevo?

2020-10-28 07:11 UTC, infabeti commented on src/main/java/modelo/LeerOds.java
> +			VariablesEstaticas.MatrizAuxiliarString = new String[nFilas + 6][nColumnas];
Porque no creais un método que aumente de manera dinámica

2020-10-28 07:13 UTC, infabeti commented on src/main/java/modelo/LeerOdt.java
> +		}
Crea un único método. Así, no cambias código.

2020-10-28 07:22 UTC, infabeti requested changes
Pequeñas cosas por pulir

2020-10-28 07:22 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		ControladorGesDocx contenidoFichDocx = new ControladorGesDocx();
sobra

2020-10-28 07:40 UTC, khrixthian commented on src/main/java/modelo/AgregarAlTxt.java
> +			aux = auxorigen + nuevoFormateado;
hecho.

2020-10-28 07:52 UTC, khrixthian commented on src/main/java/modelo/LeerOdt.java
> +		}
hecho

2020-10-28 08:37 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscDocxTest.java
> +		ControladorGesDocx contenidoFichDocx = new ControladorGesDocx();
hecho

2020-10-28 09:01 UTC, DiegoVJElorrieta commented on src/main/java/modelo/VariablesEstaticas.java
> +	public static String[][] MatrizAuxiliarString;
Arreglado

2020-10-28 23:01 UTC, DiegoVJElorrieta commented on src/main/java/modelo/LeerOds.java
> +			VariablesEstaticas.MatrizAuxiliarString = new String[nFilas + 6][nColumnas];
Cambiado

2020-10-29 07:14 UTC, infabeti commented on src/main/java/controlador/ControladorGesOds.java
> +	public String[][] mostrarOds() {
Modifica esto, para que la clase leerOds te entre como parametro

2020-10-29 07:17 UTC, infabeti commented on src/main/java/controlador/ControladorUser.java
> +		return control;
Cambia el código para que se pueda mockear modeloUserr

2020-10-29 07:19 UTC, infabeti commented on src/main/java/modelo/VariablesEstaticas.java
> +	public String[][] MatrizAuxiliarString;
Te sigue haciendo falta la variable MatrizAuxiliarString?

2020-10-29 07:21 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				scrollPane.setViewportView(textPane);
Declarar todo arriba por favor

2020-10-29 07:22 UTC, infabeti commented on src/main/java/vista/VentanaConsultas.java
> +				ControladorGesEscDocx escritor = new ControladorGesEscDocx(agregarAlDocx);
Ponedle mejores nombres

2020-10-29 07:26 UTC, infabeti commented on src/test/java/controlador/ControladorGesEscTxtTest.java
> +		try {
En un test no se deben hacerse try

2020-10-29 07:29 UTC, infabeti requested changes
Arregladme esto por favor

2020-10-29 08:29 UTC, DiegoVJElorrieta commented on src/main/java/modelo/VariablesEstaticas.java
> +	public String[][] MatrizAuxiliarString;
Eliminada

2020-10-29 08:32 UTC, DiegoVJElorrieta commented on src/main/java/controlador/ControladorGesOds.java
> +	public String[][] mostrarOds() {
Hecho

2020-10-29 08:46 UTC, DiegoVJElorrieta commented on src/main/java/vista/VentanaConsultas.java
> +				scrollPane.setViewportView(textPane);
Hecho

2020-10-29 16:47 UTC, infabeti requested changes
Os falta quitar el try de ControladorGesEscTxtTest y Cambiar ControladorUser para que puedas mockear modeloUsers

2020-10-29 17:11 UTC, khrixthian commented on src/test/java/controlador/ControladorGesEscTxtTest.java
> +		try {
hecho

2020-10-29 17:15 UTC, khrixthian commented on src/main/java/vista/VentanaConsultas.java
> +				ControladorGesEscDocx escritor = new ControladorGesEscDocx(agregarAlDocx);
hecho

2020-10-29 18:58 UTC, khrixthian commented on src/main/java/controlador/ControladorUser.java
> +		return control;
cambiado tanto el ControladorUser como su test

2020-10-30 07:15 UTC, infabeti commented on src/main/java/controlador/ControladorGesOds.java
> +	public String[][] mostrarOds(LeerOds leerOds) {
Cambio 1

2020-10-30 07:15 UTC, infabeti requested changes
Solo faltan dos cambios

2020-10-30 07:18 UTC, infabeti commented on src/test/java/controlador/ControladorGesOdsTest.java
> +		testString = "prueba";
Cambio 2

2020-10-30 07:51 UTC, DiegoVJElorrieta commented on src/main/java/controlador/ControladorGesOds.java
> +	public String[][] mostrarOds(LeerOds leerOds) {
Hecho

2020-10-30 08:09 UTC, khrixthian commented on src/test/java/controlador/ControladorGesOdsTest.java
> +		testString = "prueba";
hecho

2020-10-30 08:17 UTC, infabeti approved these changes

2020-10-30 08:17 UTC, merged